### PR TITLE
Update versions and make the results reproducible

### PR DESCRIPTION
**Pull request by adamretter**
1. We update to the latest version of the CSV Parsers (per JDK version).
2. Maven profiles are used to ensure the correct version for each JDK version.
3. Parsers are now correctly configured for different file encodings.
4. The build and results are now reproducible using:

    ```bash
    $ git clone https://github.com/uniVocity/csv-parsers-comparison.git
    $ cd csv-parsers-comparison
    $ wget http://www.maxmind.com/download/worldcities/worldcitiespop.txt.gz
    $ gunzip worldcitiespop.txt.gz
    $ mvn clean package
    $ jar target/csv-parsers-comparison-1.0-uber.jar .
    ```

    NOTE: the `.` at the end of the last command, this tells Java the folder containing the `worldcitiespop.txt`. You can alternatively specify a path to any folder that contains a `worldcitiespop.txt` file.

### CODE REVIEW

**Comment by jbax** [comment]
Thanks a lot for your contribution! I'll test and update the results tomorrow.

**Comment by jbax** [comment]
Hi @adamretter, the maven build is not suceeding, do you have any suggestion? Here is the output I'm getting:

[jbax@linux-pc csv-parsers-comparison]$ mvn clean install -e
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building csv-parsers-comparison 1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ csv-parsers-comparison ---
[INFO] Deleting /home/jbax/dev/repository/csv-parsers-comparison/target
[INFO] 
[INFO] --- maven-patch-plugin:1.2:apply (patch) @ csv-parsers-comparison ---
[INFO] Applying patch: esperio-csv-6.x.patch
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.786 s
[INFO] Finished at: 2017-10-08T01:46:22+10:30
[INFO] Final Memory: 11M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-patch-plugin:1.2:apply (patch) on project csv-parsers-comparison: Patch command failed with exit code 1 for esperio-csv-6.x.patch. Please see console and debug output for more information. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-patch-plugin:1.2:apply (patch) on project csv-parsers-comparison: Patch command failed with exit code 1 for esperio-csv-6.x.patch. Please see console and debug output for more information.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Patch command failed with exit code 1 for esperio-csv-6.x.patch. Please see console and debug output for more information.
        at org.apache.maven.plugin.patch.ApplyMojo.applyPatches(ApplyMojo.java:447)
        at org.apache.maven.plugin.patch.ApplyMojo.execute(ApplyMojo.java:288)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more

**Comment by adamretter** [comment]
The patch can only be applied once.

You might need to git checkout -- the src folder.

**Comment by jbax** [comment]
Thanks but it doesn't work. I'll just get rid of that parser and call it a day

**Comment by jbax** [comment]
The command to run the app also doesn't seem to work (at least on linux)

[jbax@linux-pc csv-parsers-comparison]$ java -jar target/csv-parsers-comparison-1.0-uber.jar .
Exception in thread "main" java.lang.IllegalArgumentException: URI is not hierarchical
        at java.io.File.<init>(File.java:418)
        at com.univocity.articles.csvcomparison.PerformanceComparison.main(PerformanceComparison.java:163)

**Comment by adamretter** [comment]
Okay I will take a look on a VM here I built and tested on Mac.

I could also send a PR to support Travis, which could help catch these
things?

**Pull request merged**
